from typing import Protocol, Dict, Optional, Any
from .domain import VaultHeader, LoadResult

class VaultFileProtocol(Protocol):
    header: VaultHeader
    secrets: Dict[str, str]

class EnvStoreProtocol(Protocol):
    def get(self, key: str, default: Optional[str] = None) -> Optional[str]: ...
    def get_or_throw(self, key: str) -> str: ...
    def is_initialized(self) -> bool: ...
    def on_startup(self, env_file: str = ".env") -> LoadResult: ...
