#!/usr/bin/env python3
"""
python .bin/sync-dockerfile-pythonpath.py

Scans packages_py/ and fastapi_apps/ directories and updates Dockerfile.fastapi
with the correct PYTHONPATH environment variable.

Usage:
    python .bin/sync-dockerfile-pythonpath.py [--dry-run]

Options:
    --dry-run    Show what would be changed without modifying files
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


def get_script_root() -> Path:
    """Get the monorepo root directory."""
    return Path(__file__).resolve().parent.parent


def find_python_paths(root: Path) -> list[str]:
    """Find all PYTHONPATH entries for Docker container paths."""
    paths = []

    # packages_py/*/src
    packages_py = root / 'packages_py'
    if packages_py.exists():
        for pkg in sorted(packages_py.iterdir()):
            if pkg.is_dir() and not pkg.name.startswith(('.', '_')):
                src_dir = pkg / 'src'
                if src_dir.exists():
                    paths.append(f"/applications/packages_py/{pkg.name}/src")

    # fastapi_apps/*
    fastapi_apps = root / 'fastapi_apps'
    if fastapi_apps.exists():
        for app in sorted(fastapi_apps.iterdir()):
            if app.is_dir() and not app.name.startswith(('.', '_')):
                if (app / 'pyproject.toml').exists():
                    paths.append(f"/applications/fastapi_apps/{app.name}")

    return paths


def generate_pythonpath_env(paths: list[str]) -> str:
    """Generate multi-line ENV PYTHONPATH statement."""
    if not paths:
        return 'ENV PYTHONPATH=""'

    # Single path case
    if len(paths) == 1:
        return f'ENV PYTHONPATH="{paths[0]}"'

    # Multi-path case with line continuations
    lines = [f'ENV PYTHONPATH="{paths[0]}:\\']
    for path in paths[1:-1]:
        lines.append(f'{path}:\\')
    lines.append(f'{paths[-1]}"')

    return '\n'.join(lines)


def update_dockerfile(dockerfile_path: Path, paths: list[str], dry_run: bool = False) -> bool:
    """Update Dockerfile with new PYTHONPATH."""
    content = dockerfile_path.read_text()

    # Look for marker comment
    marker = "# PYTHONPATH - auto-generated by sync-dockerfile-pythonpath.py"

    if marker not in content:
        print(f"ERROR: Marker not found in {dockerfile_path}")
        print(f"Please add this comment before the ENV PYTHONPATH line:")
        print(f"  {marker}")
        print(f"  ENV PYTHONPATH=\"...\"")
        return False

    # Pattern to match marker + ENV PYTHONPATH block (handles multi-line)
    # Matches from marker through the closing quote of PYTHONPATH
    pattern = re.compile(
        r'# PYTHONPATH - auto-generated by sync-dockerfile-pythonpath\.py\nENV PYTHONPATH="[^"]*"',
        re.DOTALL
    )

    new_block = marker + '\n' + generate_pythonpath_env(paths)
    new_content = pattern.sub(new_block, content)

    if new_content == content:
        print("Dockerfile is already up to date.")
        return False

    if not dry_run:
        dockerfile_path.write_text(new_content)

    return True


def main():
    parser = argparse.ArgumentParser(
        description='Sync PYTHONPATH in Dockerfile.fastapi with packages_py/ and fastapi_apps/'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Show what would be changed without modifying files'
    )
    args = parser.parse_args()

    root = get_script_root()
    dockerfile = root / 'Dockerfile.fastapi'

    print(f"Scanning: {root / 'packages_py'}")
    print(f"Scanning: {root / 'fastapi_apps'}")
    print(f"Target:   {dockerfile}")
    print()

    if not dockerfile.exists():
        print(f"ERROR: Dockerfile.fastapi not found at {dockerfile}")
        sys.exit(1)

    paths = find_python_paths(root)
    print(f"Found {len(paths)} paths:")
    for p in paths:
        print(f"  - {p}")
    print()

    changed = update_dockerfile(dockerfile, paths, dry_run=args.dry_run)

    if changed:
        if args.dry_run:
            print("DRY RUN: No changes made. Run without --dry-run to apply.")
        else:
            print("Dockerfile.fastapi updated successfully.")
            print()
            print("Next steps:")
            print("  1. Review the changes in Dockerfile.fastapi")
            print("  2. Rebuild your Docker image")


if __name__ == '__main__':
    main()
