# Base configuration for testing
app:
  name: test-app
  version: 1.0.0
  environment: test

providers:
  anthropic:
    api_key: null
    model: claude-3-opus
    max_tokens: 4096
  openai:
    api_key: null
    model: gpt-4

services:
  database:
    host: localhost
    port: 5432
    name: testdb
  cache:
    host: localhost
    port: 6379

storages:
  local:
    path: /tmp/storage
  s3:
    bucket: test-bucket
    region: us-east-1

global:
  timeout: 30000
  retry_count: 3
